name: client CI
on: [push]

jobs:
  js-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
      - name: Install deps
        working-directory: client
        run: npm install
      - name: Run linter
        working-directory: client
        run: npm run lint
